# Generated by Django 5.0.14 on 2025-08-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7)),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.quote')),
            ],
            options={
                'indexes': [models.Index(fields=['quote', 'session_key'], name='quotes_vote_quote_i_1a817a_idx'), models.Index(fields=['quote', 'ip_address'], name='quotes_vote_quote_i_0fb392_idx')],
            },
        ),
    ]
